In [3]:
import pandas as pd

In [5]:
df_sheet_name1 = pd.read_excel('ukraine.xlsx', sheet_name='Importers_2020')
print(df_sheet_name1)

     Importer M.49 Importer ISO3            Importer  \
0              818           EGY               Egypt
1              360           IDN           Indonesia
2               50           BGD          Bangladesh
3              792           TUR              Turkey
4              586           PAK            Pakistan
..             ...           ...                 ...
116            136           CYM      Cayman Islands
117             70           BIH  Bosnia Herzegovina
118            340           HND            Honduras
119            428           LVA              Latvia
120            899           NaN          Areas, nes

                                  Importer region Resource  Year  \
0                Northern Africa and Western Asia    Wheat  2020
1    Eastern and South-Eastern Asia (excl. China)    Wheat  2020
2                       Central and Southern Asia    Wheat  2020
3                Northern Africa and Western Asia    Wheat  2020
4                       Central and Southern Asia    Wheat  2020
..                                            ...      ...   ...
116               Latin America and the Caribbean    Wheat  2020
117                                        Europe    Wheat  2020
118               Latin America and the Caribbean    Wheat  2020
119                                        Europe    Wheat  2020
120                                           NaN    Wheat  2020

     Value (1000USD)  Weight (1000kg)  Unnamed: 8
0       1.302692e+06     5.541816e+06         NaN
1       6.562987e+05     2.886787e+06         NaN
2       2.948471e+05     1.514725e+06         NaN
3       3.102935e+05     1.495828e+06         NaN
4       3.228615e+05     1.294414e+06         NaN
..               ...              ...         ...
116     1.000000e-02     2.500000e-02         NaN
117     1.700000e-02     1.200000e-02         NaN
118     6.000000e-03     1.000000e-02         NaN
119     2.000000e-03     5.000000e-03         NaN
120     5.300000e-02     3.000000e-03         NaN

[121 rows x 9 columns]

In [6]:
df1 = pd.DataFrame(df_sheet_name1)
df1

,Importer M.49,Importer ISO3,Importer,Importer region,Resource,Year,Value (1000USD),Weight (1000kg),Unnamed: 8
0,818,EGY,Egypt,Northern Africa and Western Asia,Wheat,2020,1.302692e+06,5.541816e+06,NaN
1,360,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),Wheat,2020,6.562987e+05,2.886787e+06,NaN
2,50,BGD,Bangladesh,Central and Southern Asia,Wheat,2020,2.948471e+05,1.514725e+06,NaN
3,792,TUR,Turkey,Northern Africa and Western Asia,Wheat,2020,3.102935e+05,1.495828e+06,NaN
4,586,PAK,Pakistan,Central and Southern Asia,Wheat,2020,3.228615e+05,1.294414e+06,NaN
...,...,...,...,...,...,...,...,...,...
116,136,CYM,Cayman Islands,Latin America and the Caribbean,Wheat,2020,1.000000e-02,2.500000e-02,NaN
117,70,BIH,Bosnia Herzegovina,Europe,Wheat,2020,1.700000e-02,1.200000e-02,NaN
118,340,HND,Honduras,Latin America and the Caribbean,Wheat,2020,6.000000e-03,1.000000e-02,NaN
119,428,LVA,Latvia,Europe,Wheat,2020,2.000000e-03,5.000000e-03,NaN
120,899,NaN,"Areas, nes",NaN,Wheat,2020,5.300000e-02,3.000000e-03,NaN

In [7]:
df2 = df1.rename(columns={df1.columns[1]:'country_code',
                          df1.columns[2]:'importer',
                         df1.columns[3]:'importer_region',
                         df1.columns[6]:'value_for_ukraine',
                         df1.columns[7]:'weight_for_ukraine'})

df2

,Importer M.49,country_code,importer,importer_region,Resource,Year,value_for_ukraine,weight_for_ukraine,Unnamed: 8
0,818,EGY,Egypt,Northern Africa and Western Asia,Wheat,2020,1.302692e+06,5.541816e+06,NaN
1,360,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),Wheat,2020,6.562987e+05,2.886787e+06,NaN
2,50,BGD,Bangladesh,Central and Southern Asia,Wheat,2020,2.948471e+05,1.514725e+06,NaN
3,792,TUR,Turkey,Northern Africa and Western Asia,Wheat,2020,3.102935e+05,1.495828e+06,NaN
4,586,PAK,Pakistan,Central and Southern Asia,Wheat,2020,3.228615e+05,1.294414e+06,NaN
...,...,...,...,...,...,...,...,...,...
116,136,CYM,Cayman Islands,Latin America and the Caribbean,Wheat,2020,1.000000e-02,2.500000e-02,NaN
117,70,BIH,Bosnia Herzegovina,Europe,Wheat,2020,1.700000e-02,1.200000e-02,NaN
118,340,HND,Honduras,Latin America and the Caribbean,Wheat,2020,6.000000e-03,1.000000e-02,NaN
119,428,LVA,Latvia,Europe,Wheat,2020,2.000000e-03,5.000000e-03,NaN
120,899,NaN,"Areas, nes",NaN,Wheat,2020,5.300000e-02,3.000000e-03,NaN

In [8]:
df3 = df2[['country_code','importer','importer_region','value_for_ukraine','weight_for_ukraine']].copy()
df3

,country_code,importer,importer_region,value_for_ukraine,weight_for_ukraine
0,EGY,Egypt,Northern Africa and Western Asia,1.302692e+06,5.541816e+06
1,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),6.562987e+05,2.886787e+06
2,BGD,Bangladesh,Central and Southern Asia,2.948471e+05,1.514725e+06
3,TUR,Turkey,Northern Africa and Western Asia,3.102935e+05,1.495828e+06
4,PAK,Pakistan,Central and Southern Asia,3.228615e+05,1.294414e+06
...,...,...,...,...,...
116,CYM,Cayman Islands,Latin America and the Caribbean,1.000000e-02,2.500000e-02
117,BIH,Bosnia Herzegovina,Europe,1.700000e-02,1.200000e-02
118,HND,Honduras,Latin America and the Caribbean,6.000000e-03,1.000000e-02
119,LVA,Latvia,Europe,2.000000e-03,5.000000e-03
120,NaN,"Areas, nes",NaN,5.300000e-02,3.000000e-03

In [10]:
df_sheet_name2 = pd.read_excel('russia.xlsx', sheet_name='Importers_2020')
print(df_sheet_name2)

     Importer M.49 Importer ISO3       Importer  \
0                4           AFG    Afghanistan
1                8           ALB        Albania
2               24           AGO         Angola
3               31           AZE     Azerbaijan
4               36           AUS      Australia
..             ...           ...            ...
110            834           TZA       Tanzania
111            842           USA  United States
112            854           BFA   Burkina Faso
113            860           UZB     Uzbekistan
114            887           YEM          Yemen

                      Importer region Resource  Year  Value (1000USD)  \
0           Central and Southern Asia    Wheat  2020      3243.339000
1                              Europe    Wheat  2020     35917.133000
2                  Sub-Saharan Africa    Wheat  2020     46093.797000
3    Northern Africa and Western Asia    Wheat  2020    290906.746663
4           Australia and New Zealand    Wheat  2020      2445.328000
..                                ...      ...   ...              ...
110                Sub-Saharan Africa    Wheat  2020    154878.720000
111                  Northern America    Wheat  2020     14092.708604
112                Sub-Saharan Africa    Wheat  2020      1866.550000
113         Central and Southern Asia    Wheat  2020     10300.916732
114  Northern Africa and Western Asia    Wheat  2020    174314.480000

     Weight (1000kg)
0       1.194915e+04
1       1.520579e+05
2       1.996523e+05
3       1.369706e+06
4       1.647591e+03
..               ...
110     7.009114e+05
111     1.007337e+04
112     6.937950e+03
113     3.016893e+04
114     7.961034e+05

[115 rows x 8 columns]

In [11]:
df4 = pd.DataFrame(df_sheet_name2)
df4

,Importer M.49,Importer ISO3,Importer,Importer region,Resource,Year,Value (1000USD),Weight (1000kg)
0,4,AFG,Afghanistan,Central and Southern Asia,Wheat,2020,3243.339000,1.194915e+04
1,8,ALB,Albania,Europe,Wheat,2020,35917.133000,1.520579e+05
2,24,AGO,Angola,Sub-Saharan Africa,Wheat,2020,46093.797000,1.996523e+05
3,31,AZE,Azerbaijan,Northern Africa and Western Asia,Wheat,2020,290906.746663,1.369706e+06
4,36,AUS,Australia,Australia and New Zealand,Wheat,2020,2445.328000,1.647591e+03
...,...,...,...,...,...,...,...,...
110,834,TZA,Tanzania,Sub-Saharan Africa,Wheat,2020,154878.720000,7.009114e+05
111,842,USA,United States,Northern America,Wheat,2020,14092.708604,1.007337e+04
112,854,BFA,Burkina Faso,Sub-Saharan Africa,Wheat,2020,1866.550000,6.937950e+03
113,860,UZB,Uzbekistan,Central and Southern Asia,Wheat,2020,10300.916732,3.016893e+04
114,887,YEM,Yemen,Northern Africa and Western Asia,Wheat,2020,174314.480000,7.961034e+05

In [12]:
df5 = df4.rename(columns={df4.columns[1]:'country_code',
                          df4.columns[2]:'importer',
                         df4.columns[3]:'importer_region',
                         df4.columns[6]:'value_for_russia',
                         df4.columns[7]:'weight_for_russia'})

df5

,Importer M.49,country_code,importer,importer_region,Resource,Year,value_for_russia,weight_for_russia
0,4,AFG,Afghanistan,Central and Southern Asia,Wheat,2020,3243.339000,1.194915e+04
1,8,ALB,Albania,Europe,Wheat,2020,35917.133000,1.520579e+05
2,24,AGO,Angola,Sub-Saharan Africa,Wheat,2020,46093.797000,1.996523e+05
3,31,AZE,Azerbaijan,Northern Africa and Western Asia,Wheat,2020,290906.746663,1.369706e+06
4,36,AUS,Australia,Australia and New Zealand,Wheat,2020,2445.328000,1.647591e+03
...,...,...,...,...,...,...,...,...
110,834,TZA,Tanzania,Sub-Saharan Africa,Wheat,2020,154878.720000,7.009114e+05
111,842,USA,United States,Northern America,Wheat,2020,14092.708604,1.007337e+04
112,854,BFA,Burkina Faso,Sub-Saharan Africa,Wheat,2020,1866.550000,6.937950e+03
113,860,UZB,Uzbekistan,Central and Southern Asia,Wheat,2020,10300.916732,3.016893e+04
114,887,YEM,Yemen,Northern Africa and Western Asia,Wheat,2020,174314.480000,7.961034e+05

In [13]:
df6 = df5[['country_code','importer','importer_region','value_for_russia','weight_for_russia']].copy()
df6

,country_code,importer,importer_region,value_for_russia,weight_for_russia
0,AFG,Afghanistan,Central and Southern Asia,3243.339000,1.194915e+04
1,ALB,Albania,Europe,35917.133000,1.520579e+05
2,AGO,Angola,Sub-Saharan Africa,46093.797000,1.996523e+05
3,AZE,Azerbaijan,Northern Africa and Western Asia,290906.746663,1.369706e+06
4,AUS,Australia,Australia and New Zealand,2445.328000,1.647591e+03
...,...,...,...,...,...
110,TZA,Tanzania,Sub-Saharan Africa,154878.720000,7.009114e+05
111,USA,United States,Northern America,14092.708604,1.007337e+04
112,BFA,Burkina Faso,Sub-Saharan Africa,1866.550000,6.937950e+03
113,UZB,Uzbekistan,Central and Southern Asia,10300.916732,3.016893e+04
114,YEM,Yemen,Northern Africa and Western Asia,174314.480000,7.961034e+05

In [14]:
df7=df3[['country_code','importer','importer_region','value_for_ukraine','weight_for_ukraine']]
df7

,country_code,importer,importer_region,value_for_ukraine,weight_for_ukraine
0,EGY,Egypt,Northern Africa and Western Asia,1.302692e+06,5.541816e+06
1,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),6.562987e+05,2.886787e+06
2,BGD,Bangladesh,Central and Southern Asia,2.948471e+05,1.514725e+06
3,TUR,Turkey,Northern Africa and Western Asia,3.102935e+05,1.495828e+06
4,PAK,Pakistan,Central and Southern Asia,3.228615e+05,1.294414e+06
...,...,...,...,...,...
116,CYM,Cayman Islands,Latin America and the Caribbean,1.000000e-02,2.500000e-02
117,BIH,Bosnia Herzegovina,Europe,1.700000e-02,1.200000e-02
118,HND,Honduras,Latin America and the Caribbean,6.000000e-03,1.000000e-02
119,LVA,Latvia,Europe,2.000000e-03,5.000000e-03
120,NaN,"Areas, nes",NaN,5.300000e-02,3.000000e-03

In [15]:
df8=df6[['country_code','importer','importer_region','value_for_russia','weight_for_russia']]
df8

,country_code,importer,importer_region,value_for_russia,weight_for_russia
0,AFG,Afghanistan,Central and Southern Asia,3243.339000,1.194915e+04
1,ALB,Albania,Europe,35917.133000,1.520579e+05
2,AGO,Angola,Sub-Saharan Africa,46093.797000,1.996523e+05
3,AZE,Azerbaijan,Northern Africa and Western Asia,290906.746663,1.369706e+06
4,AUS,Australia,Australia and New Zealand,2445.328000,1.647591e+03
...,...,...,...,...,...
110,TZA,Tanzania,Sub-Saharan Africa,154878.720000,7.009114e+05
111,USA,United States,Northern America,14092.708604,1.007337e+04
112,BFA,Burkina Faso,Sub-Saharan Africa,1866.550000,6.937950e+03
113,UZB,Uzbekistan,Central and Southern Asia,10300.916732,3.016893e+04
114,YEM,Yemen,Northern Africa and Western Asia,174314.480000,7.961034e+05

In [16]:
df9 = pd.merge(df7, df8, on='country_code', how='left')
df9

,country_code,importer_x,importer_region_x,value_for_ukraine,weight_for_ukraine,importer_y,importer_region_y,value_for_russia,weight_for_russia
0,EGY,Egypt,Northern Africa and Western Asia,1.302692e+06,5.541816e+06,Egypt,Northern Africa and Western Asia,3.424248e+06,1.404519e+07
1,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),6.562987e+05,2.886787e+06,Indonesia,Eastern and South-Eastern Asia (excl. China),1.081354e+04,4.785343e+04
2,BGD,Bangladesh,Central and Southern Asia,2.948471e+05,1.514725e+06,Bangladesh,Central and Southern Asia,4.088716e+05,1.940910e+06
3,TUR,Turkey,Northern Africa and Western Asia,3.102935e+05,1.495828e+06,Turkey,Northern Africa and Western Asia,1.716829e+06,7.842940e+06
4,PAK,Pakistan,Central and Southern Asia,3.228615e+05,1.294414e+06,Pakistan,Central and Southern Asia,3.148377e+05,1.183592e+06
...,...,...,...,...,...,...,...,...,...
116,CYM,Cayman Islands,Latin America and the Caribbean,1.000000e-02,2.500000e-02,NaN,NaN,NaN,NaN
117,BIH,Bosnia Herzegovina,Europe,1.700000e-02,1.200000e-02,NaN,NaN,NaN,NaN
118,HND,Honduras,Latin America and the Caribbean,6.000000e-03,1.000000e-02,NaN,NaN,NaN,NaN
119,LVA,Latvia,Europe,2.000000e-03,5.000000e-03,Latvia,Europe,7.542778e+04,3.756515e+05
120,NaN,"Areas, nes",NaN,5.300000e-02,3.000000e-03,NaN,NaN,NaN,NaN

In [19]:
df10 = df9.drop(['importer_y'],axis=1)
df10

,country_code,importer_x,importer_region_x,value_for_ukraine,weight_for_ukraine,importer_region_y,value_for_russia,weight_for_russia
0,EGY,Egypt,Northern Africa and Western Asia,1.302692e+06,5.541816e+06,Northern Africa and Western Asia,3.424248e+06,1.404519e+07
1,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),6.562987e+05,2.886787e+06,Eastern and South-Eastern Asia (excl. China),1.081354e+04,4.785343e+04
2,BGD,Bangladesh,Central and Southern Asia,2.948471e+05,1.514725e+06,Central and Southern Asia,4.088716e+05,1.940910e+06
3,TUR,Turkey,Northern Africa and Western Asia,3.102935e+05,1.495828e+06,Northern Africa and Western Asia,1.716829e+06,7.842940e+06
4,PAK,Pakistan,Central and Southern Asia,3.228615e+05,1.294414e+06,Central and Southern Asia,3.148377e+05,1.183592e+06
...,...,...,...,...,...,...,...,...
116,CYM,Cayman Islands,Latin America and the Caribbean,1.000000e-02,2.500000e-02,NaN,NaN,NaN
117,BIH,Bosnia Herzegovina,Europe,1.700000e-02,1.200000e-02,NaN,NaN,NaN
118,HND,Honduras,Latin America and the Caribbean,6.000000e-03,1.000000e-02,NaN,NaN,NaN
119,LVA,Latvia,Europe,2.000000e-03,5.000000e-03,Europe,7.542778e+04,3.756515e+05
120,NaN,"Areas, nes",NaN,5.300000e-02,3.000000e-03,NaN,NaN,NaN

In [20]:
df11 = df10.drop(['importer_region_y'],axis=1)
df11

,country_code,importer_x,importer_region_x,value_for_ukraine,weight_for_ukraine,value_for_russia,weight_for_russia
0,EGY,Egypt,Northern Africa and Western Asia,1.302692e+06,5.541816e+06,3.424248e+06,1.404519e+07
1,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),6.562987e+05,2.886787e+06,1.081354e+04,4.785343e+04
2,BGD,Bangladesh,Central and Southern Asia,2.948471e+05,1.514725e+06,4.088716e+05,1.940910e+06
3,TUR,Turkey,Northern Africa and Western Asia,3.102935e+05,1.495828e+06,1.716829e+06,7.842940e+06
4,PAK,Pakistan,Central and Southern Asia,3.228615e+05,1.294414e+06,3.148377e+05,1.183592e+06
...,...,...,...,...,...,...,...
116,CYM,Cayman Islands,Latin America and the Caribbean,1.000000e-02,2.500000e-02,NaN,NaN
117,BIH,Bosnia Herzegovina,Europe,1.700000e-02,1.200000e-02,NaN,NaN
118,HND,Honduras,Latin America and the Caribbean,6.000000e-03,1.000000e-02,NaN,NaN
119,LVA,Latvia,Europe,2.000000e-03,5.000000e-03,7.542778e+04,3.756515e+05
120,NaN,"Areas, nes",NaN,5.300000e-02,3.000000e-03,NaN,NaN

In [21]:
df12 = df11.rename(columns={df11.columns[1]:'importer',
                          df11.columns[2]:'importer_region'})
df12

,country_code,importer,importer_region,value_for_ukraine,weight_for_ukraine,value_for_russia,weight_for_russia
0,EGY,Egypt,Northern Africa and Western Asia,1.302692e+06,5.541816e+06,3.424248e+06,1.404519e+07
1,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),6.562987e+05,2.886787e+06,1.081354e+04,4.785343e+04
2,BGD,Bangladesh,Central and Southern Asia,2.948471e+05,1.514725e+06,4.088716e+05,1.940910e+06
3,TUR,Turkey,Northern Africa and Western Asia,3.102935e+05,1.495828e+06,1.716829e+06,7.842940e+06
4,PAK,Pakistan,Central and Southern Asia,3.228615e+05,1.294414e+06,3.148377e+05,1.183592e+06
...,...,...,...,...,...,...,...
116,CYM,Cayman Islands,Latin America and the Caribbean,1.000000e-02,2.500000e-02,NaN,NaN
117,BIH,Bosnia Herzegovina,Europe,1.700000e-02,1.200000e-02,NaN,NaN
118,HND,Honduras,Latin America and the Caribbean,6.000000e-03,1.000000e-02,NaN,NaN
119,LVA,Latvia,Europe,2.000000e-03,5.000000e-03,7.542778e+04,3.756515e+05
120,NaN,"Areas, nes",NaN,5.300000e-02,3.000000e-03,NaN,NaN

In [30]:
#Display only rows that refer to Asia's imports from either Ukraine or Russia, without including China's imports
df13 = df12[df12['importer_region'].str.contains('Asia', na=False)]
df13

,country_code,importer,importer_region,value_for_ukraine,weight_for_ukraine,value_for_russia,weight_for_russia
0,EGY,Egypt,Northern Africa and Western Asia,1.302692e+06,5.541816e+06,3.424248e+06,1.404519e+07
1,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),6.562987e+05,2.886787e+06,1.081354e+04,4.785343e+04
2,BGD,Bangladesh,Central and Southern Asia,2.948471e+05,1.514725e+06,4.088716e+05,1.940910e+06
3,TUR,Turkey,Northern Africa and Western Asia,3.102935e+05,1.495828e+06,1.716829e+06,7.842940e+06
4,PAK,Pakistan,Central and Southern Asia,3.228615e+05,1.294414e+06,3.148377e+05,1.183592e+06
5,TUN,Tunisia,Northern Africa and Western Asia,1.943768e+05,9.840161e+05,2.398304e+04,1.112668e+05
6,MAR,Morocco,Northern Africa and Western Asia,2.028144e+05,9.421935e+05,1.003948e+05,4.264859e+05
7,LBN,Lebanon,Northern Africa and Western Asia,1.691254e+05,7.632033e+05,5.707770e+04,2.522689e+05
8,YEM,Yemen,Northern Africa and Western Asia,1.444446e+05,7.084188e+05,1.743145e+05,7.961034e+05
9,PHL,Philippines,Eastern and South-Eastern Asia (excl. China),1.347996e+05,6.349188e+05,1.162101e+05,5.486915e+05
10,THA,Thailand,Eastern and South-Eastern Asia (excl. China),1.224258e+05,5.696764e+05,6.853644e+04,3.099317e+05
11,LBY,Libya,Northern Africa and Western Asia,1.090394e+05,5.469909e+05,3.744809e+04,1.706985e+05
12,KOR,"Korea, Republic",Eastern and South-Eastern Asia (excl. China),8.394169e+04,4.134038e+05,1.511313e+04,5.884004e+04
13,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),9.046283e+04,3.785548e+05,1.213295e+04,5.392267e+04
15,JOR,Jordan,Northern Africa and Western Asia,8.400055e+04,3.580070e+05,7.936050e+04,3.469010e+05
16,VNM,Vietnam,Eastern and South-Eastern Asia (excl. China),5.486301e+04,2.507777e+05,1.637427e+05,6.722776e+05
19,ISR,Israel,Northern Africa and Western Asia,2.650848e+04,1.285622e+05,4.027193e+04,2.017356e+05
20,LKA,Sri Lanka,Central and Southern Asia,2.846149e+04,1.143832e+05,1.223409e+05,5.045930e+05
21,SDN,Sudan,Northern Africa and Western Asia,2.392462e+04,1.096990e+05,2.829358e+05,1.333409e+06
22,ARE,United Arab Emirates,Northern Africa and Western Asia,2.742062e+04,9.694140e+04,1.678082e+05,6.859705e+05
23,QAT,Qatar,Northern Africa and Western Asia,2.087994e+04,9.515078e+04,6.050039e+03,2.257347e+04
29,MMR,Myanmar,Eastern and South-Eastern Asia (excl. China),1.666928e+04,6.910385e+04,1.010178e+03,4.182780e+03
30,SAU,Saudi Arabia,Northern Africa and Western Asia,1.323788e+04,6.441307e+04,6.996969e+04,3.082200e+05
35,PSE,State of Palestine,Northern Africa and Western Asia,1.864076e+04,4.011690e+04,3.575747e+03,1.327262e+04
42,OMN,Oman,Northern Africa and Western Asia,5.331381e+03,2.417537e+04,8.874892e+04,4.290952e+05
46,CYP,Cyprus,Northern Africa and Western Asia,2.395760e+03,1.257123e+04,2.057082e+03,8.075567e+03
51,SGP,Singapore,Eastern and South-Eastern Asia (excl. China),1.321792e+03,5.402235e+03,5.919000e+00,1.084300e+01
52,DZA,Algeria,Northern Africa and Western Asia,1.358099e+03,5.400000e+03,NaN,NaN
57,LAO,Lao PDR,Eastern and South-Eastern Asia (excl. China),5.832000e+02,3.069760e+03,NaN,NaN
67,GEO,Georgia,Northern Africa and Western Asia,1.811783e+02,6.010124e+02,1.087384e+05,5.433183e+05
70,KHM,Cambodia,Eastern and South-Eastern Asia (excl. China),8.616715e+01,3.654000e+02,1.377000e+02,4.500000e+02
71,IRQ,Iraq,Northern Africa and Western Asia,7.786600e+01,2.715080e+02,1.111177e+03,4.270650e+03
76,KWT,Kuwait,Northern Africa and Western Asia,4.590388e+01,1.712650e+02,1.000840e+02,3.517500e+02
78,AZE,Azerbaijan,Northern Africa and Western Asia,5.730580e+01,1.282465e+02,2.909067e+05,1.369706e+06
84,KAZ,Kazakhstan,Central and Southern Asia,5.667513e+01,8.870000e+01,9.228236e+04,5.960223e+05
87,TKM,Turkmenistan,Central and Southern Asia,3.916400e+01,6.716200e+01,5.316277e+03,2.364579e+04
93,ARM,Armenia,Northern Africa and Western Asia,1.221800e+01,2.500000e+01,7.450288e+04,3.703315e+05
112,JPN,Japan,Eastern and South-Eastern Asia (excl. China),8.000000e-02,8.000000e-02,4.934909e+00,6.988426e+00

In [32]:
df14 = df13.reset_index().drop(['index'],axis=1)

df14

,country_code,importer,importer_region,value_for_ukraine,weight_for_ukraine,value_for_russia,weight_for_russia
0,EGY,Egypt,Northern Africa and Western Asia,1.302692e+06,5.541816e+06,3.424248e+06,1.404519e+07
1,IDN,Indonesia,Eastern and South-Eastern Asia (excl. China),6.562987e+05,2.886787e+06,1.081354e+04,4.785343e+04
2,BGD,Bangladesh,Central and Southern Asia,2.948471e+05,1.514725e+06,4.088716e+05,1.940910e+06
3,TUR,Turkey,Northern Africa and Western Asia,3.102935e+05,1.495828e+06,1.716829e+06,7.842940e+06
4,PAK,Pakistan,Central and Southern Asia,3.228615e+05,1.294414e+06,3.148377e+05,1.183592e+06
5,TUN,Tunisia,Northern Africa and Western Asia,1.943768e+05,9.840161e+05,2.398304e+04,1.112668e+05
6,MAR,Morocco,Northern Africa and Western Asia,2.028144e+05,9.421935e+05,1.003948e+05,4.264859e+05
7,LBN,Lebanon,Northern Africa and Western Asia,1.691254e+05,7.632033e+05,5.707770e+04,2.522689e+05
8,YEM,Yemen,Northern Africa and Western Asia,1.444446e+05,7.084188e+05,1.743145e+05,7.961034e+05
9,PHL,Philippines,Eastern and South-Eastern Asia (excl. China),1.347996e+05,6.349188e+05,1.162101e+05,5.486915e+05
10,THA,Thailand,Eastern and South-Eastern Asia (excl. China),1.224258e+05,5.696764e+05,6.853644e+04,3.099317e+05
11,LBY,Libya,Northern Africa and Western Asia,1.090394e+05,5.469909e+05,3.744809e+04,1.706985e+05
12,KOR,"Korea, Republic",Eastern and South-Eastern Asia (excl. China),8.394169e+04,4.134038e+05,1.511313e+04,5.884004e+04
13,MYS,Malaysia,Eastern and South-Eastern Asia (excl. China),9.046283e+04,3.785548e+05,1.213295e+04,5.392267e+04
14,JOR,Jordan,Northern Africa and Western Asia,8.400055e+04,3.580070e+05,7.936050e+04,3.469010e+05
15,VNM,Vietnam,Eastern and South-Eastern Asia (excl. China),5.486301e+04,2.507777e+05,1.637427e+05,6.722776e+05
16,ISR,Israel,Northern Africa and Western Asia,2.650848e+04,1.285622e+05,4.027193e+04,2.017356e+05
17,LKA,Sri Lanka,Central and Southern Asia,2.846149e+04,1.143832e+05,1.223409e+05,5.045930e+05
18,SDN,Sudan,Northern Africa and Western Asia,2.392462e+04,1.096990e+05,2.829358e+05,1.333409e+06
19,ARE,United Arab Emirates,Northern Africa and Western Asia,2.742062e+04,9.694140e+04,1.678082e+05,6.859705e+05
20,QAT,Qatar,Northern Africa and Western Asia,2.087994e+04,9.515078e+04,6.050039e+03,2.257347e+04
21,MMR,Myanmar,Eastern and South-Eastern Asia (excl. China),1.666928e+04,6.910385e+04,1.010178e+03,4.182780e+03
22,SAU,Saudi Arabia,Northern Africa and Western Asia,1.323788e+04,6.441307e+04,6.996969e+04,3.082200e+05
23,PSE,State of Palestine,Northern Africa and Western Asia,1.864076e+04,4.011690e+04,3.575747e+03,1.327262e+04
24,OMN,Oman,Northern Africa and Western Asia,5.331381e+03,2.417537e+04,8.874892e+04,4.290952e+05
25,CYP,Cyprus,Northern Africa and Western Asia,2.395760e+03,1.257123e+04,2.057082e+03,8.075567e+03
26,SGP,Singapore,Eastern and South-Eastern Asia (excl. China),1.321792e+03,5.402235e+03,5.919000e+00,1.084300e+01
27,DZA,Algeria,Northern Africa and Western Asia,1.358099e+03,5.400000e+03,NaN,NaN
28,LAO,Lao PDR,Eastern and South-Eastern Asia (excl. China),5.832000e+02,3.069760e+03,NaN,NaN
29,GEO,Georgia,Northern Africa and Western Asia,1.811783e+02,6.010124e+02,1.087384e+05,5.433183e+05
30,KHM,Cambodia,Eastern and South-Eastern Asia (excl. China),8.616715e+01,3.654000e+02,1.377000e+02,4.500000e+02
31,IRQ,Iraq,Northern Africa and Western Asia,7.786600e+01,2.715080e+02,1.111177e+03,4.270650e+03
32,KWT,Kuwait,Northern Africa and Western Asia,4.590388e+01,1.712650e+02,1.000840e+02,3.517500e+02
33,AZE,Azerbaijan,Northern Africa and Western Asia,5.730580e+01,1.282465e+02,2.909067e+05,1.369706e+06
34,KAZ,Kazakhstan,Central and Southern Asia,5.667513e+01,8.870000e+01,9.228236e+04,5.960223e+05
35,TKM,Turkmenistan,Central and Southern Asia,3.916400e+01,6.716200e+01,5.316277e+03,2.364579e+04
36,ARM,Armenia,Northern Africa and Western Asia,1.221800e+01,2.500000e+01,7.450288e+04,3.703315e+05
37,JPN,Japan,Eastern and South-Eastern Asia (excl. China),8.000000e-02,8.000000e-02,4.934909e+00,6.988426e+00

In [33]:
df14.shape

(38, 7)

In [35]:
#How many total tones of wheat have been imported in Europe from both Ukraine and Russia?
df15 = df12[df12['importer_region'].str.contains('Europe', na=False)]
df15

,country_code,importer,importer_region,value_for_ukraine,weight_for_ukraine,value_for_russia,weight_for_russia
14,ESP,Spain,Europe,73961.860000,372993.800000,5502.407776,21450.026076
17,ITA,Italy,Europe,46240.056000,228202.443000,25582.500000,94691.522000
25,GRC,Greece,Europe,18479.531347,87043.860005,34032.837047,144540.560825
39,MDA,Moldova,Europe,8849.380079,31815.493622,1181.854894,3872.405306
40,GBR,United Kingdom,Europe,8392.348495,31230.173150,5561.746000,17348.305000
41,NLD,Netherlands,Europe,7452.483070,26564.155397,1476.390070,2507.424100
43,RUS,Russian Federation,Europe,2276.409949,23335.977900,NaN,NaN
44,ALB,Albania,Europe,5471.283700,22126.787000,35917.133000,152057.920000
47,DEU,Germany,Europe,3995.556825,11882.783463,163.827245,418.121548
48,CHE,Switzerland,Europe,2760.309400,11154.046000,11295.911234,54937.602180
50,EST,Estonia,Europe,1032.300000,6150.148000,2.601774,0.859366
54,POL,Poland,Europe,1220.191633,3962.454931,467.977280,1059.092000
55,BLR,Belarus,Europe,1127.471950,3896.045200,9999.727656,40910.562760
69,ROU,Romania,Europe,74.153508,388.524000,10670.838000,56159.020000
72,AUT,Austria,Europe,139.888835,270.862875,NaN,NaN
73,NOR,Norway,Europe,161.050447,265.730000,43567.670000,54357.877000
80,MLT,Malta,Europe,31.574463,107.247220,2122.066000,8388.025000
85,CZE,Czech Republic,Europe,18.386674,70.792064,NaN,NaN
88,MKD,North Macedonia,Europe,16.302000,66.000000,176.250000,579.830000
91,SRB,Serbia,Europe,10.831000,39.002000,71.677766,139.204510
92,SVK,Slovakia,Europe,12.546259,27.699000,0.675000,0.800000
95,DNK,Denmark,Europe,5.846000,24.201000,929.956000,3300.000000
98,LTU,Lithuania,Europe,1.714698,3.456000,20177.211000,95806.424000
100,FRA,France,Europe,0.759525,1.700000,0.016000,0.077000
102,BGR,Bulgaria,Europe,0.368000,0.657000,2020.200825,9361.895000
109,HRV,Croatia,Europe,0.099000,0.100000,NaN,NaN
111,MNE,Montenegro,Europe,0.048565,0.082516,0.007000,0.006000
117,BIH,Bosnia Herzegovina,Europe,0.017000,0.012000,NaN,NaN
119,LVA,Latvia,Europe,0.002000,0.005000,75427.781625,375651.496552

In [36]:
df16 = df15.reset_index().drop(['index'],axis=1)
df16

,country_code,importer,importer_region,value_for_ukraine,weight_for_ukraine,value_for_russia,weight_for_russia
0,ESP,Spain,Europe,73961.860000,372993.800000,5502.407776,21450.026076
1,ITA,Italy,Europe,46240.056000,228202.443000,25582.500000,94691.522000
2,GRC,Greece,Europe,18479.531347,87043.860005,34032.837047,144540.560825
3,MDA,Moldova,Europe,8849.380079,31815.493622,1181.854894,3872.405306
4,GBR,United Kingdom,Europe,8392.348495,31230.173150,5561.746000,17348.305000
5,NLD,Netherlands,Europe,7452.483070,26564.155397,1476.390070,2507.424100
6,RUS,Russian Federation,Europe,2276.409949,23335.977900,NaN,NaN
7,ALB,Albania,Europe,5471.283700,22126.787000,35917.133000,152057.920000
8,DEU,Germany,Europe,3995.556825,11882.783463,163.827245,418.121548
9,CHE,Switzerland,Europe,2760.309400,11154.046000,11295.911234,54937.602180
10,EST,Estonia,Europe,1032.300000,6150.148000,2.601774,0.859366
11,POL,Poland,Europe,1220.191633,3962.454931,467.977280,1059.092000
12,BLR,Belarus,Europe,1127.471950,3896.045200,9999.727656,40910.562760
13,ROU,Romania,Europe,74.153508,388.524000,10670.838000,56159.020000
14,AUT,Austria,Europe,139.888835,270.862875,NaN,NaN
15,NOR,Norway,Europe,161.050447,265.730000,43567.670000,54357.877000
16,MLT,Malta,Europe,31.574463,107.247220,2122.066000,8388.025000
17,CZE,Czech Republic,Europe,18.386674,70.792064,NaN,NaN
18,MKD,North Macedonia,Europe,16.302000,66.000000,176.250000,579.830000
19,SRB,Serbia,Europe,10.831000,39.002000,71.677766,139.204510
20,SVK,Slovakia,Europe,12.546259,27.699000,0.675000,0.800000
21,DNK,Denmark,Europe,5.846000,24.201000,929.956000,3300.000000
22,LTU,Lithuania,Europe,1.714698,3.456000,20177.211000,95806.424000
23,FRA,France,Europe,0.759525,1.700000,0.016000,0.077000
24,BGR,Bulgaria,Europe,0.368000,0.657000,2020.200825,9361.895000
25,HRV,Croatia,Europe,0.099000,0.100000,NaN,NaN
26,MNE,Montenegro,Europe,0.048565,0.082516,0.007000,0.006000
27,BIH,Bosnia Herzegovina,Europe,0.017000,0.012000,NaN,NaN
28,LVA,Latvia,Europe,0.002000,0.005000,75427.781625,375651.496552